### ISSUE TITLE
Milestone 2 Feedback (Pilot studies)

### ISSUE THREAD

**Issue by bxie** [info370/project-dataplus#3]
Great questions and decision contexts to investigate!
Some feedback: 

# College acceptance
Think about your decision context. Who do you want to inform and about what? If you find a relationship between household income and college acceptance, what decision do you intend to inform? This should help focus your data exploration.

# Yelp data
Yelp shares a rich dataset via their [Yelp data challenge](https://www.yelp.com/dataset/challenge). You may want to check that out. Alternatively, grab Greg or me if you're having API troubles. I'm curious the differences in user base between Yelp and Google Places...

Some ways to further focus your thinking:
- who are the stakeholders who want to inform? Focusing on informing consumers vs city officials (for example) changes your study.
- what do you want to optimize?

(no further action is required for this "issue" and you can close it after you've reviewed it)

**Comment by greglnelson** [comment]
It looks like you did some difficult work and learned more about data cleaning and exploration, particularly with the Dept of Ed dataset. So I applaud you there - and your problem solving with respect to R for the restaurants.

I echo Benji's decision context points. Right now you're starting from a research question that is answerable in maybe 10 hours of work, which isn't enough for the project for this class.

It is unclear to me that the college dataset can answer the "acceptance decision" question. Does that dataset show all the colleges each person applied to, and whether they got in or not? Or does it show the college each person ended up attending. If it doesn't contain rejections, you can't tell if colleges are accepting people at different rates based on income. 

While I think it is good to check this kind of data, many colleges state they have a "needs blind" admission process. It might be interesting to look at institutions that are not needs blind and compare them. Still, what decision what that question inform? 

If you're having trouble thinking of a decision to advise, step back, don't consider what data is available, and try to generate as many decisions as possible (regardless of feasibility). When you do that, send it to me and I'll give some more feedback.

I also see you narrowing the question you're considering (in the potential questions you had "Have 4-year universities in the US taken an effort to diversify their college campus via applicant's acceptance/admission?" and now it is "To what extent does household income impact the decision for colleges to accept a student to the campus?" That second question is a more narrow question, and, while it's important to have that skill (to narrow) when doing data science, at this stage of the process you're narrowing too much. The broad and narrow is a hard to balance - at this stage, you should put more time into looking for several different data sources and how you might join/combine them together to answer more decision-oriented questions.

I'm also curious if you developed your 5 uncertainties first (for each question) and then answered them, or if you did data exploration. This is not about grading or points, and I'd really appreciate an honest answer here, so I can understand what's hard about the project.
